### ISSUE TITLE
[Bug]: Unable to connect with client credentials authentication flow

### ISSUE THREAD

**Issue by silverhack** [silverhack/monkey365#51]
**What happened?**  

Depending on the scopes defined in the Azure AD application, the Client Credentials grant type will be unable to connect to specific resources. Monkey365 relies also on metadata from the `old` Microsoft Graph to get information from tenants. Right now client credentials grant type is affected by this issue. 

**How to reproduce it**  

Execute Monkey365 with the Client Credential authentication Flow and include SharePointOnline, ExchangeOnline, Purview in the analysis parameter
Multiple 401 and 403 status code are returned by Monkey365

**Expected behavior**
The Client Credentials authentication flow is supported by both, the deprecated old Graph and Microsoft Graph API. Monkey365 should migrate from old Graph api to Microsoft Graph. 

Applications with Graph API permissions are not affected by this issue.

**Comment by Mastix95** [comment]
Hello @silverhack 

I'm also having the same issue authenticating against the AAD with the Graph permissions for Sharepoint Online, I'm not sure if I'm not granting the appropiate permissions. Could you pinpoint me where are this permissions documented?

Thank you in advance.

**Comment by silverhack** [comment]
[Fixed](https://github.com/silverhack/monkey365/commit/7871e37c152bc4863f3a24d713a9804a170ef4ca) on dev branch

**Comment by silverhack** [comment]
> Hello @silverhack 
> 
> 
> 
> I'm also having the same issue authenticating against the AAD with the Graph permissions for Sharepoint Online, I'm not sure if I'm not granting the appropiate permissions. Could you pinpoint me where are this permissions documented?
> 
> 
> 
> Thank you in advance.

Hi it is documented [here](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)

Cheers

**Comment by silverhack** [comment]
Hi @DM01187, 

This is caused by the [Get-LabelPolicy](https://learn.microsoft.com/en-us/powershell/module/exchange/get-labelpolicy?view=exchange-ps), so you can safely ignore this warning.

**Comment by DM01187** [comment]
I still have a small problem:
WARNUNG: [12:32:51:955] - [Get-MonkeyCSOMSitesForUser] - Unable to get site properties using "xyz" account - warning - S25111 - SPSUnableToGetSites

Is there anything additional that needs to be specified here?

Thank you in advance.

**Comment by silverhack** [comment]
It's now fixed on dev branch. It will be merged to main branch asap
